name: Create Release on Merge

on:
  push:
    branches:
      - main

jobs:
  release:
    if: "contains(github.event.head_commit.message, 'Update to v')"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract version from commit message
        id: get_version
        run: |
          # Extracts '1.4.319' from a commit message like "Update to v1.4.319"
          VERSION=$(echo "${{ github.event.head_commit.message }}" | cut -d 'v' -f 2 | awk '{print $1}')
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Create GitHub Release and Tag
        if: steps.get_version.outputs.version
        run: |
          gh release create "v${{ steps.get_version.outputs.version }}" \
            --title "Release v${{ steps.get_version.outputs.version }}" \
            --generate-notes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}