name: 'Update'

on:
  workflow_dispatch:

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update script
        run: python3 update.py

      - name: Extract version from pyproject.toml
        id: get_version
        run: |
          echo "version=$(grep 'version = ' pyproject.toml | cut -d '"' -f 2)" >> "$GITHUB_OUTPUT"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: "v${{ steps.get_version.outputs.version }}"
          commit-message: "Update to v${{ steps.get_version.outputs.version }}"
          title: "Update to v${{ steps.get_version.outputs.version }}"
          author: GitHub <noreply@github.com>
          delete-branch: true

      - name: enable pr automerge
        run: |
          sleep 60
          gh pr merge --merge --auto ${{env.PULL_REQUEST_NUMBER}}
        env:
          GH_TOKEN: ${{ github.token }}
        continue-on-error: true
